apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-ui
          image: frontendapp:v1
          ports:
            - containerPort: 80
