apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-persistent-volume
spec:
  storageClassName: redis-class
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500M
  hostPath:
    path: /k8s/volumes/