apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: redis
spec:
  storageClassName: redis-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500M