apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: spring-now-api
          image: backendapp:v1
          ports:
            - containerPort: 8080
          env:
          - name: "REDIS_HOST"
            value: redis-service
          - name: "REDIS_PORT"
            value: "6379"
          - name: "REDIS_PASSWORD"
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: redis_password
          - name: TZ
            value: "Asia/Riyadh"

          readinessProbe:
            httpGet:
              path: /monitoring/ready
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 2
